// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortShipTrackingSystem.Infrastructure.Data;

#nullable disable

namespace PortShipTrackingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoId"));

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightTon")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CargoId");

                    b.HasIndex("ShipId");

                    b.ToTable("Cargoes");
                });

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.CrewMember", b =>
                {
                    b.Property<int>("CrewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrewId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrewId");

                    b.ToTable("CrewMembers");
                });

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.Port", b =>
                {
                    b.Property<int>("PortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortId");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.Ship", b =>
                {
                    b.Property<int>("shipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shipId"));

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMO")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("shipId");

                    b.HasIndex("IMO")
                        .IsUnique();

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.ShipCrewAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrewId")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("CrewId");

                    b.HasIndex("ShipId", "CrewId", "AssignmentDate")
                        .IsUnique();

                    b.ToTable("ShipCrewAssignments");
                });

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.ShipVisit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("VisitId");

                    b.HasIndex("PortId");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipVisits");
                });

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.Cargo", b =>
                {
                    b.HasOne("PortShipTrackingSystem.Core.Entities.Ship", "Ship")
                        .WithMany("Cargoes")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.ShipCrewAssignment", b =>
                {
                    b.HasOne("PortShipTrackingSystem.Core.Entities.CrewMember", "Crew")
                        .WithMany("ShipCrewAssignments")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortShipTrackingSystem.Core.Entities.Ship", "Ship")
                        .WithMany("ShipCrewAssignments")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.ShipVisit", b =>
                {
                    b.HasOne("PortShipTrackingSystem.Core.Entities.Port", "Port")
                        .WithMany("ShipVisits")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortShipTrackingSystem.Core.Entities.Ship", "Ship")
                        .WithMany("ShipVisits")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.CrewMember", b =>
                {
                    b.Navigation("ShipCrewAssignments");
                });

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.Port", b =>
                {
                    b.Navigation("ShipVisits");
                });

            modelBuilder.Entity("PortShipTrackingSystem.Core.Entities.Ship", b =>
                {
                    b.Navigation("Cargoes");

                    b.Navigation("ShipCrewAssignments");

                    b.Navigation("ShipVisits");
                });
#pragma warning restore 612, 618
        }
    }
}
